package com.kuronami.welcomeboard.seen;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Pure read/revision logic for "has this player already seen this content" decisions.
 * Deliberately separated from {@link SeenFileStore} so the decision itself is testable
 * without touching a filesystem. Calc layer: no Minecraft types.
 *
 * <p>Data shape: {@code scopeKey -> contentId -> lastSeenRevision}. {@code scopeKey}
 * identifies a server/world and is generated by the loader-specific layer (this class
 * only ever receives it as an opaque string) — this is what keeps "seen" state from
 * leaking across servers, which was the regression in the prior-art mods this design
 * responds to.</p>
 */
public final class SeenStateEvaluator {

    private SeenStateEvaluator() {
    }

    /**
     * @return true if the content should be shown: either it has never been recorded for
     *         this scope, or the given revision is newer than the last-seen one.
     */
    public static boolean shouldShow(Map<String, Map<String, Integer>> data, String scopeKey, String contentId, int revision) {
        if (data == null || scopeKey == null || contentId == null) {
            return true;
        }
        Map<String, Integer> scope = data.get(scopeKey);
        if (scope == null) {
            return true;
        }
        Integer lastSeenRevision = scope.get(contentId);
        if (lastSeenRevision == null) {
            return true;
        }
        return revision > lastSeenRevision;
    }

    /**
     * Returns a new map (input is left untouched) with {@code contentId} recorded as seen
     * at {@code revision} for {@code scopeKey}.
     */
    public static Map<String, Map<String, Integer>> markSeen(Map<String, Map<String, Integer>> data,
                                                               String scopeKey, String contentId, int revision) {
        Map<String, Map<String, Integer>> copy = new LinkedHashMap<>();
        if (data != null) {
            for (Map.Entry<String, Map<String, Integer>> entry : data.entrySet()) {
                copy.put(entry.getKey(), new LinkedHashMap<>(entry.getValue()));
            }
        }
        copy.computeIfAbsent(scopeKey, key -> new LinkedHashMap<>()).put(contentId, revision);
        return copy;
    }
}
